#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
import optparse
import sys

def process(line, attributes):

    data = json.loads(line)
    results = {}

    if attributes:
        ref = data
        for attrib in attributes:
            for part in attrib.split('.'):
                if part in ref:
                    ref = ref[part]
            if ref:
                results[attrib] = ref
    else:
        results = data
          
    print json.dumps(results)


def main():
    usage = "usage: %prog [options]"
    parser = optparse.OptionParser(usage=usage)

    parser.add_option("-d", "--default", metavar="NUMBER", type="float", 
        help="if specified it will be used for null/undef values")

    parser.add_option("-p", "--pretty", action="store_true", default=False,
        help="output will be pretty json")

    (options, args) = parser.parse_args()
    
    for line in sys.stdin.readlines():
        process(line.strip(), args)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)


